apiVersion: v1
kind: ConfigMap
metadata:
  name: alperconfig

data:
    siabElasticApi.properties: |-
        searchServerPort={{ .Values.elasticsearch.searchServerPort }}
        elastic_search_url={{ .Values.elasticsearch.url }}
        elastic_search_address={{ .Values.elasticsearch.address }}
        elastic_search_port={{ .Values.elasticsearch.port }}
        elastic_index_format={{ .Values.elasticsearch.elasticIndexFormat }}
    log4j2.xml: |-
        <?xml version="1.0" encoding="UTF-8"?><Configuration status="warn"><Properties><Property name="basePath">.</Property></Properties><Appenders><RollingFile name="fileLogger" fileName="${basePath}/logs/siabElasticApi.log"filePattern="${basePath}/logs/siab-elastic-api-%d{yyyy-MM-dd}.log"><PatternLayout><pattern>[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] (%F:%L) - %msg%n</pattern></PatternLayout><Policies><TimeBasedTriggeringPolicy interval="1" modulate="true" /></Policies></RollingFile><Console name="console" target="SYSTEM_OUT"><PatternLayout pattern="[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] (%F:%L) - %msg%n" /></Console></Appenders><Loggers><Logger name="org.netsia" level="debug" additivity="true"><appender-ref ref="fileLogger" level="debug" /></Logger><Root level="debug" additivity="false"><appender-ref ref="console" /></Root></Loggers></Configuration>

