apiVersion: v1
kind: ConfigMap
metadata:
  name: alperconfig

data:
    siabElasticApi.properties: |-
        searchServerPort={{ .Values.elasticsearch.searchServerPort }}
        elastic_search_url={{ .Values.elasticsearch.url }}
        elastic_search_address={{ .Values.elasticsearch.address }}
        elastic_search_port={{ .Values.elasticsearch.port }}
        elastic_index_format={{ .Values.elasticsearch.elasticIndexFormat }}
    log4j2.properties: |-
        status = error
        name = PropertiesConfig
        #Make sure to change log file path as per your need
        property.filename = ./logs/siabElasticApi.log
        filters = threshold
        filter.threshold.type = ThresholdFilter
        filter.threshold.level = debug
        appenders = rolling
        appender.rolling.type = RollingFile
        appender.rolling.name = RollingFile
        appender.rolling.fileName = ${filename}
        appender.rolling.filePattern = debug-backup-%d{MM-dd-yy-HH-mm-ss}-%i.log.gz
        appender.rolling.layout.type = PatternLayout
        appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
        appender.rolling.policies.type = Policies
        appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
        appender.rolling.policies.time.interval = 1
        appender.rolling.policies.time.modulate = true
        appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
        appender.rolling.policies.size.size=10MB
        appender.rolling.strategy.type = DefaultRolloverStrategy
        appender.rolling.strategy.max = 20
        loggers = rolling
        logger.rolling.name = org.netsia
        logger.rolling.level = debug
        #logger.rolling.additivity = false
        logger.rolling.appenderRef.rolling.ref = RollingFile
